"""Added price to Bus

Revision ID: c378a249577e
Revises: 4ed15eed3461
Create Date: 2025-02-01 15:48:33.893615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c378a249577e'
down_revision = '4ed15eed3461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
